#  Copyright (c) 2024 Feng Yang
#
#  I am making my contributions/submissions to this project solely in my
#  personal capacity and am not conveying any rights to any intellectual
#  property of any third parties.
from PySide6 import QtWidgets
from vtkmodules.vtkFiltersSources import vtkCylinderSource

from SpatialView import VtkCylinderSourceModel

class VtkCylinderSource:
    def __init__(self, model: VtkCylinderSourceModel):
        self._source: vtkCylinderSource = None
        self._model: VtkCylinderSourceModel = None

    @property
    def radius(self) -> float: ...
    @radius.setter
    def radius(self, value: float): ...
    @property
    def radiusMax(self) -> float: ...
    @property
    def radiusMin(self) -> float: ...
    @property
    def height(self) -> float: ...
    @property
    def heightMax(self) -> float: ...
    @property
    def heightMin(self) -> float: ...
    @height.setter
    def height(self, height: float): ...
    @property
    def resolution(self) -> int: ...
    @property
    def resolutionMax(self) -> int: ...
    @property
    def resolutionMin(self) -> int: ...
    @resolution.setter
    def resolution(self, value: int): ...
    @property
    def capping(self) -> bool: ...
    @capping.setter
    def capping(self, value: bool): ...
    @property
    def capsuleCap(self) -> bool: ...
    @capsuleCap.setter
    def capsuleCap(self, value: bool): ...
    @property
    def center(self): ...
    @center.setter
    def center(self, value): ...
    def dialog(self) -> QtWidgets.QDialog: ...
    def outputPort(self): ...
    def load(self, p): ...
    def save(self): ...
