#  Copyright (c) 2024 Feng Yang
#
#  I am making my contributions/submissions to this project solely in my
#  personal capacity and am not conveying any rights to any intellectual
#  property of any third parties.
from vtkmodules.vtkRenderingCore import vtkMapper, vtkTexture
from vtkmodules.vtkRenderingOpenGL2 import vtkOpenGLSkybox

class VtkOpenGLSkybox:
    def __init__(self):
        self._skybox: vtkOpenGLSkybox = None

    @property
    def texture(self) -> vtkTexture: ...
    @texture.setter
    def texture(self, value: vtkTexture): ...
    @property
    def projection(self) -> int: ...
    @projection.setter
    def projection(self, value: int): ...
    @property
    def floorPlane(self) -> tuple[float, float, float, float]: ...
    @floorPlane.setter
    def floorPlane(self, value: tuple[float, float, float, float]): ...
    @property
    def floorRight(self) -> tuple[float, float, float]: ...
    @floorRight.setter
    def floorRight(self, value: tuple[float, float, float]): ...
    @property
    def gammaCorrect(self) -> bool: ...
    @gammaCorrect.setter
    def gammaCorrect(self, value: bool): ...
    # =========== Mapper ======================================================
    @property
    def mapper(self) -> vtkMapper: ...
    @mapper.setter
    def mapper(self, value: vtkMapper): ...
